[fix] resolve package conflict
Pinning joblib to version 1.3.2 solves the following error:
`ImportError: cannot import name 'parallel_config' from
'joblib.parallel'`.